name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --name postgres --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PostgreSQL
      run: |
        echo "Waiting for PostgreSQL to start..."
        dockerize -wait tcp://localhost:5432 -timeout 1m
        echo "PostgreSQL is up and running!"

    - name: Run your tests or other CI tasks
      run: |
        echo "hugo"
