name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --name postgres --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and install dbmate
      run: |
        curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
        chmod +x /usr/local/bin/dbmate

    - name: Install PostgreSQL and client
      run: |
        apt-get update
        apt-get install postgresql -y
        apt-get install postgresql-client -y

    - name: Run migrations and dump data
      run: |
        make migrate
        make dump_ci
        mv db/schema.sql postgres_test.sql

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: postgres_test_sql
        path: postgres_test.sql
