name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.0
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --name postgres --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and install dbmate
      run: |
        curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
        chmod +x /usr/local/bin/dbmate

    - name: Run migrations and dump data
      run: |
        make migrate
        make dump_ci
        mv db/schema.sql postgres_test.sql

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: postgres_test_sql
        path: postgres_test.sql

  documentation:
    runs-on: ubuntu-latest
    needs: build
    
    services:
      postgres:
        image: postgres:15.0
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configure l'environnement pour SchemaSpy
        run: |
          apt-get update
          apt-get install default-jdk -y
          apt-get install postgresql-client -y
          apt-get install graphviz -y
         

      - name: Exécuter SchemaSpy
        run: |
          java -jar schemaspy-6.2.4.jar -configFile config.file -debug
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation-artifact
          path: public
